version: 2.1

orbs:
  node: circleci/node@5.0.3

jobs:
  build:
    docker:
      - image: cimg/node:19.1.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run Build
          command: npm run build

workflows:
  sample:
    jobs:
      - build
