version: 2.1

jobs:
  pull-and-build:
    docker:
      - image: arvindr226/alpine-ssh:latest
    steps:
      - checkout
      - run: ssh -oStrictHostKeyChecking=no -v $USER@$IP "./vam-vam-tech-deploy.sh"

workflows:
  build-project:
    jobs:
      - pull-and-build:
          filters:
            branches:
              only:
                - main
# VS Code Extension Version: 1.4.0